name: RPM

on: [push]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install build-essential

      - name: Cache apt packages
        id: apt-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-deb-test
          restore-keys: |
            ${{ runner.os }}-deb-test

      - name: Create temporary artifact folder
        run: mkdir artifacts

      - name: Upload artifacts for workflow
        uses: actions/upload-artifact@v3
        with: 
            name: artifacts
            path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: artifacts/test-${{ github.ref_name }}.tar.gz
